#!/bin/bash
# build-libc-baremetal.sh - Build picolibc for M65832 baremetal
#
# Builds picolibc with MMIO-based syscalls for running on the emulator
# or FPGA hardware without an operating system.
#
# Usage: ./build-libc-baremetal.sh [--clean|--rebuild]

set -e

# Source common configuration
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/common.sh"

# ============================================================================
# Configuration
# ============================================================================

BUILD_ACTION="${1:-build}"
STDLIB_DIR="$LLVM_SRC/m65832-stdlib"

# ============================================================================
# Functions
# ============================================================================

check_dependencies() {
    log_info "Checking dependencies..."
    
    # Check LLVM is built
    if [ ! -x "$CLANG" ]; then
        log_error "Clang not found at $CLANG"
        log_info "Run: ./scripts/build-llvm.sh --fast"
        exit 1
    fi
    
    # Check LLD is built
    if [ ! -x "$LLD" ]; then
        log_error "LLD not found at $LLD"
        log_info "Run: ./scripts/build-llvm.sh --full"
        exit 1
    fi
    
    # Check picolibc source exists
    if [ ! -d "$PICOLIBC_SRC" ]; then
        log_error "Picolibc source not found at $PICOLIBC_SRC"
        log_info "Run: ./scripts/clone-deps.sh --picolibc"
        exit 1
    fi
    
    log_success "Dependencies OK"
}

generate_cross_file() {
    log_info "Generating Meson cross-compilation file..."
    
    local cross_file="$PICOLIBC_BUILD/cross-m65832-baremetal.txt"
    mkdir -p "$PICOLIBC_BUILD"
    
    # Create clang wrapper
    local clang_wrapper="$PICOLIBC_BUILD/m65832-clang"
    cat > "$clang_wrapper" << EOF
#!/bin/bash
# Wrapper for clang that adds M65832 target flags
exec $CLANG \\
    -target m65832-elf \\
    -ffreestanding \\
    -fuse-ld=lld \\
    "\$@"
EOF
    chmod +x "$clang_wrapper"
    
    # Create cross-compilation file
    cat > "$cross_file" << EOF
# Meson cross-compilation file for M65832 baremetal
# Auto-generated by build-libc-baremetal.sh

[constants]
stdlib_dir = '$STDLIB_DIR'

[binaries]
c = '$clang_wrapper'
ar = '$LLVM_AR'
as = '$clang_wrapper'
ld = '$LLD'
strip = 'strip'
ranlib = '$LLVM_RANLIB'

[built-in options]
# Note: -g disabled due to debug info crash in MCAssembler::layout()
# Note: -O2+ disabled due to analyzeBranch() crash in BranchFolder
c_args = ['-O1']
c_link_args = ['-nostdlib']

[host_machine]
system = 'none'
cpu_family = 'm65832'
cpu = 'm65832'
endian = 'little'

[properties]
skip_sanity_check = true
EOF
    
    log_success "Cross-compilation file generated"
}

build_picolibc() {
    log_section "Building Picolibc for Baremetal"
    
    local cross_file="$PICOLIBC_BUILD/cross-m65832-baremetal.txt"
    
    # Configure with meson
    log_info "Configuring picolibc..."
    meson setup "$PICOLIBC_BUILD" "$PICOLIBC_SRC" \
        --cross-file "$cross_file" \
        --prefix="$SYSROOT_BAREMETAL" \
        --buildtype=plain \
        -Ddebug=false \
        -Doptimization=1 \
        -Dmultilib=false \
        -Dtests=false \
        -Dspecsdir=none \
        -Dfreestanding=true
    
    # Build
    log_info "Building picolibc..."
    meson compile -C "$PICOLIBC_BUILD" -j "$JOBS"
    
    # Install
    log_info "Installing picolibc..."
    meson install -C "$PICOLIBC_BUILD"
    
    log_success "Picolibc build complete"
}

install_m65832_files() {
    log_section "Installing M65832-specific Files"
    
    local lib_dir="$SYSROOT_BAREMETAL/lib"
    local inc_dir="$SYSROOT_BAREMETAL/include"
    
    mkdir -p "$lib_dir" "$inc_dir"
    
    # Compile syscalls
    log_info "Compiling syscalls.c..."
    "$CLANG" -target m65832-elf -ffreestanding -O1 \
        -I"$inc_dir" \
        -c "$STDLIB_DIR/picolibc/syscalls.c" -o "$lib_dir/syscalls.o"
    
    # Assemble crt0
    log_info "Assembling crt0.s..."
    "$CLANG" -target m65832-elf -ffreestanding \
        -c "$STDLIB_DIR/picolibc/crt0.s" -o "$lib_dir/crt0.o"
    
    # Copy linker script
    log_info "Installing linker script..."
    cp "$STDLIB_DIR/picolibc/m65832.ld" "$lib_dir/"
    
    # Create libsys.a
    log_info "Creating libsys.a..."
    "$LLVM_AR" rcs "$lib_dir/libsys.a" "$lib_dir/syscalls.o"
    
    log_success "M65832 files installed"
}

clean_build() {
    log_section "Cleaning Baremetal Build"
    
    if [ -d "$PICOLIBC_BUILD" ]; then
        log_info "Removing $PICOLIBC_BUILD..."
        rm -rf "$PICOLIBC_BUILD"
    fi
    
    if [ -d "$SYSROOT_BAREMETAL" ]; then
        log_info "Removing $SYSROOT_BAREMETAL..."
        rm -rf "$SYSROOT_BAREMETAL"
    fi
    
    log_success "Clean complete"
}

print_usage() {
    echo "Usage: $0 [OPTION]"
    echo ""
    echo "Build picolibc for M65832 baremetal"
    echo ""
    echo "Options:"
    echo "  (none)      Build picolibc"
    echo "  --rebuild   Clean and rebuild"
    echo "  --clean     Remove build directories"
    echo "  -h, --help  Show this help message"
    echo ""
    echo "Output: $SYSROOT_BAREMETAL"
}

print_summary() {
    log_section "Build Complete"
    echo "Sysroot:      $SYSROOT_BAREMETAL"
    echo "Include:      $SYSROOT_BAREMETAL/include"
    echo "Libraries:    $SYSROOT_BAREMETAL/lib"
    echo ""
    echo "To compile M65832 programs:"
    echo ""
    echo "  $CLANG -target m65832-elf -ffreestanding \\"
    echo "    -I$SYSROOT_BAREMETAL/include \\"
    echo "    -c myprogram.c -o myprogram.o"
    echo ""
    echo "  $LLD -T $SYSROOT_BAREMETAL/lib/m65832.ld \\"
    echo "    $SYSROOT_BAREMETAL/lib/crt0.o myprogram.o \\"
    echo "    -L$SYSROOT_BAREMETAL/lib -lc -lsys \\"
    echo "    -o myprogram.elf"
    echo ""
}

# ============================================================================
# Main
# ============================================================================

main() {
    case "$BUILD_ACTION" in
        build)
            check_prerequisites || exit 1
            check_dependencies
            generate_cross_file
            build_picolibc
            install_m65832_files
            print_summary
            ;;
        --rebuild)
            clean_build
            check_prerequisites || exit 1
            check_dependencies
            generate_cross_file
            build_picolibc
            install_m65832_files
            print_summary
            ;;
        --clean)
            clean_build
            ;;
        -h|--help)
            print_usage
            exit 0
            ;;
        *)
            log_error "Unknown option: $BUILD_ACTION"
            print_usage
            exit 1
            ;;
    esac
}

main "$@"
